name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the application
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    #- name: Run tests
    #  run: dotnet test --no-build --verbosity normal

    # Build Docker image
    - name: Build Docker image
      run: docker build -t jainsachin8/dockerapi:${{ github.sha }} .

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push jainsachin8/dockerapi:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    # Deploy to server (example: Azure App Service)
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: "dockerapi"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./
